# Generated by Django 3.1 on 2021-05-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default='none', null=True, upload_to='post_images/'),
        ),
    ]
